---
title: "Jupyter Lab"
output:
  html_document:
    df_print: paged
---

* Option 1: If you are using either Linux or Mac and have installed Python version>=3 and Anaconda.

* Option 2: If you are using a Windows machine or have not installed Python version>=3 and Anaconda.


# Table of Contents

* [Option 1. Installing jupyter lab](#option-1.-installing-jupyter-lab)
* [Option 2. Using jupyter lab on the web ](#option-2.-using-jupyter-lab-on-the-web)


## Option 1. Installing jupyter lab

Activate your "B216" conda environment. If you haven't done this, [follow the tutorial.](https://bitarellolab.github.io/Teaching/B216/anaconda.html)
```{bash, eval=F}
conda activate b216
```

Now install the jupyter-lab package within that environment:

```{bash, eval=F}
conda install -c conda-forge jupyterlab
```

You can now test that jupyter lab is working by typing in the command line:

```{bash, eval=F}
jupyter-lab
```

Note: if you have a terminal in your machine you can either run the commands in your machine or online. Either one is fine. 

## Option 2. Using jupyter lab on the web 

Go to the [previous step in this tutorial](https://bitarellolab.github.io/Teaching/B216/anaconda.html), follow it, and then come back here.

Now that you have an open browser with jupyter lab running,follow the instructions in this tutorial for [option 1.](#option-1.-installing-jupyter-lab)
 

## The end!